# Generated by Django 5.1.1 on 2024-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_alter_article_author_alter_article_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Makaleye Fotoğraf Ekleyin",
            ),
        ),
    ]
